export interface TypstSymbol {
  label: string   // displayed character/text
  insert: string  // Typst code to insert
  title: string   // tooltip
  icon?: string   // Typst code used for rendering the icon
}

export interface SymbolCategory {
  name: string
  symbols: TypstSymbol[]
}

export const SYMBOL_CATEGORIES: SymbolCategory[] = [
  {
    name: 'Greek',
    symbols: [
      { label: 'α', insert: 'alpha', title: 'alpha' },
      { label: 'β', insert: 'beta', title: 'beta' },
      { label: 'γ', insert: 'gamma', title: 'gamma' },
      { label: 'δ', insert: 'delta', title: 'delta' },
      { label: 'ε', insert: 'epsilon', title: 'epsilon' },
      { label: 'ζ', insert: 'zeta', title: 'zeta' },
      { label: 'η', insert: 'eta', title: 'eta' },
      { label: 'θ', insert: 'theta', title: 'theta' },
      { label: 'ι', insert: 'iota', title: 'iota' },
      { label: 'κ', insert: 'kappa', title: 'kappa' },
      { label: 'λ', insert: 'lambda', title: 'lambda' },
      { label: 'μ', insert: 'mu', title: 'mu' },
      { label: 'ν', insert: 'nu', title: 'nu' },
      { label: 'ξ', insert: 'xi', title: 'xi' },
      { label: 'π', insert: 'pi', title: 'pi' },
      { label: 'ρ', insert: 'rho', title: 'rho' },
      { label: 'σ', insert: 'sigma', title: 'sigma' },
      { label: 'τ', insert: 'tau', title: 'tau' },
      { label: 'υ', insert: 'upsilon', title: 'upsilon' },
      { label: 'φ', insert: 'phi', title: 'phi' },
      { label: 'χ', insert: 'chi', title: 'chi' },
      { label: 'ψ', insert: 'psi', title: 'psi' },
      { label: 'ω', insert: 'omega', title: 'omega' },
      { label: 'Γ', insert: 'Gamma', title: 'Gamma' },
      { label: 'Δ', insert: 'Delta', title: 'Delta' },
      { label: 'Θ', insert: 'Theta', title: 'Theta' },
      { label: 'Λ', insert: 'Lambda', title: 'Lambda' },
      { label: 'Ξ', insert: 'Xi', title: 'Xi' },
      { label: 'Π', insert: 'Pi', title: 'Pi' },
      { label: 'Σ', insert: 'Sigma', title: 'Sigma' },
      { label: 'Υ', insert: 'Upsilon', title: 'Upsilon' },
      { label: 'Φ', insert: 'Phi', title: 'Phi' },
      { label: 'Ψ', insert: 'Psi', title: 'Psi' },
      { label: 'Ω', insert: 'Omega', title: 'Omega' },
    ],
  },
  {
    name: 'Operators',
    symbols: [
      { label: '±', insert: 'plus.minus', title: 'plus-minus' },
      { label: '∓', insert: 'minus.plus', title: 'minus-plus' },
      { label: '×', insert: 'times', title: 'times' },
      { label: '÷', insert: 'div', title: 'divide' },
      { label: '·', insert: 'dot.op', title: 'dot product' },
      { label: '∘', insert: 'compose', title: 'compose' },
      { label: '⊕', insert: 'plus.circle', title: 'direct sum' },
      { label: '⊗', insert: 'times.circle', title: 'tensor product' },
      { label: '∧', insert: 'and', title: 'logical and' },
      { label: '∨', insert: 'or', title: 'logical or' },
      { label: '¬', insert: 'not', title: 'logical not' },
      { label: '⊂', insert: 'subset', title: 'subset' },
      { label: '⊃', insert: 'supset', title: 'superset' },
      { label: '⊆', insert: 'subset.eq', title: 'subset or equal' },
      { label: '⊇', insert: 'supset.eq', title: 'superset or equal' },
      { label: '∈', insert: 'in', title: 'element of' },
      { label: '∉', insert: 'in.not', title: 'not element of' },
      { label: '∩', insert: 'sect', title: 'intersection' },
      { label: '∪', insert: 'union', title: 'union' },
      { label: '∅', insert: 'emptyset', title: 'empty set' },
      { label: '≡', insert: 'equiv', title: 'equivalent' },
      { label: '≈', insert: 'approx', title: 'approximately' },
      { label: '≠', insert: 'eq.not', title: 'not equal' },
      { label: '≤', insert: 'lt.eq', title: 'less or equal' },
      { label: '≥', insert: 'gt.eq', title: 'greater or equal' },
      { label: '≪', insert: 'lt.double', title: 'much less than' },
      { label: '≫', insert: 'gt.double', title: 'much greater than' },
      { label: '∝', insert: 'prop', title: 'proportional to' },
      { label: '∼', insert: 'tilde', title: 'similar to' },
      { label: '≅', insert: 'tilde.eq', title: 'congruent' },
    ],
  },
  {
    name: 'Arrows',
    symbols: [
      { label: '→', insert: 'arrow.r', title: 'right arrow' },
      { label: '←', insert: 'arrow.l', title: 'left arrow' },
      { label: '↔', insert: 'arrow.l.r', title: 'left-right arrow' },
      { label: '⇒', insert: 'arrow.r.double', title: 'right double arrow' },
      { label: '⇐', insert: 'arrow.l.double', title: 'left double arrow' },
      { label: '⇔', insert: 'arrow.l.r.double', title: 'left-right double arrow' },
      { label: '↑', insert: 'arrow.t', title: 'up arrow' },
      { label: '↓', insert: 'arrow.b', title: 'down arrow' },
      { label: '↦', insert: 'arrow.r.bar', title: 'maps to' },
      { label: '⟶', insert: 'arrow.r.long', title: 'long right arrow' },
      { label: '⟵', insert: 'arrow.l.long', title: 'long left arrow' },
      { label: '↗', insert: 'arrow.tr', title: 'north east arrow' },
      { label: '↘', insert: 'arrow.br', title: 'south east arrow' },
      { label: '↙', insert: 'arrow.bl', title: 'south west arrow' },
      { label: '↖', insert: 'arrow.tl', title: 'north west arrow' },
    ],
  },
  {
    name: 'Trig',
    symbols: [
      // Basic
      { label: 'sin',  insert: 'sin',    title: 'sine' },
      { label: 'cos',  insert: 'cos',    title: 'cosine' },
      { label: 'tan',  insert: 'tan',    title: 'tangent' },
      { label: 'csc',  insert: 'csc',    title: 'cosecant' },
      { label: 'sec',  insert: 'sec',    title: 'secant' },
      { label: 'cot',  insert: 'cot',    title: 'cotangent' },
      // Inverse
      { label: 'arcsin', insert: 'arcsin', title: 'arcsine' },
      { label: 'arccos', insert: 'arccos', title: 'arccosine' },
      { label: 'arctan', insert: 'arctan', title: 'arctangent' },
      // Hyperbolic
      { label: 'sinh', insert: 'sinh',   title: 'hyperbolic sine' },
      { label: 'cosh', insert: 'cosh',   title: 'hyperbolic cosine' },
      { label: 'tanh', insert: 'tanh',   title: 'hyperbolic tangent' },
      { label: 'csch', insert: 'csch', title: 'hyperbolic cosecant' },
      { label: 'sech', insert: 'sech', title: 'hyperbolic secant' },
      { label: 'coth', insert: 'coth', title: 'hyperbolic cotangent' },
    ],
  },
  {
    name: 'Calculus',
    symbols: [
      { label: '∂', insert: 'partial', title: 'partial derivative' },
      { label: '∇', insert: 'nabla', title: 'nabla / gradient' },
      { label: '∞', insert: 'oo', title: 'infinity' },
      { label: '∫', insert: 'integral', title: 'integral' },
      { label: '∬', insert: 'integral.double', title: 'double integral' },
      { label: '∭', insert: 'integral.triple', title: 'triple integral' },
      { label: '∮', insert: 'integral.cont', title: 'contour integral' },
      { label: '∑', insert: 'sum', title: 'sum' },
      { label: '∏', insert: 'product', title: 'product' },
      { label: '∐', insert: 'product.co', title: 'coproduct' },
      { label: 'lim', insert: 'lim', title: 'limit' },
      { label: 'sup', insert: 'sup', title: 'supremum' },
      { label: 'inf', insert: 'inf', title: 'infimum' },
      { label: 'max', insert: 'max', title: 'maximum' },
      { label: 'min', insert: 'min', title: 'minimum' },
    ],
  },
  {
    name: 'Misc',
    symbols: [
      { label: 'ℝ', insert: 'RR', title: 'real numbers' },
      { label: 'ℤ', insert: 'ZZ', title: 'integers' },
      { label: 'ℕ', insert: 'NN', title: 'natural numbers' },
      { label: 'ℚ', insert: 'QQ', title: 'rationals' },
      { label: 'ℂ', insert: 'CC', title: 'complex numbers' },
      { label: '…', insert: 'dots.h', title: 'horizontal dots' },
      { label: '⋮', insert: 'dots.v', title: 'vertical dots' },
      { label: '⋱', insert: 'dots.down', title: 'diagonal dots' },
      { label: '⋰', insert: 'dots.up', title: 'anti-diagonal dots' },
      { label: '°', insert: 'degree', title: 'degree' },
      { label: '′', insert: 'prime', title: 'prime' },
      { label: '″', insert: 'prime.double', title: 'double prime' },
      { label: 'ℏ', insert: 'planck.reduce', title: 'reduced Planck constant' },
      { label: '†', insert: 'dagger', title: 'dagger' },
      { label: '‡', insert: 'dagger.double', title: 'double dagger' },
      { label: '★', insert: 'star', title: 'star' },
    ],
  },
]
